language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install .[test]
before_script:
  - flake8 .
script:
  - py.test -v -s --cov=ark --cov-config=.coveragerc --cov-report xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
    - develop
